<p>
The sample code handles two types of changes: 
</p>
<ul>
	<li>Parent node changes. Dragging a node into another node
	changes the node's parent node;</li>
	<li>Sort order changes. Dragging a node among its sibling
	nodes changes the node's sort order;</li>
</ul>
<p>
For demonstrates purpose, this sample only updates an in-memory
DataSet object. The code can be easily changed to update real
backend database. Please see comments in the source code for more 
details. 
</p>			
