<p>By specifying large <span class="highlight">DayCellWidth</span> and <span class="highlight">
		DayCellHeight</span> values, EO.Web Calendar can be used to create a 
	scheduler interface. The following sample demonstrates a simple read-only 
	scheduler interface. A more advanced example demonstrating an editable 
	scheduler interface is available <A href="javascript:GoToDemo('editable_scheduler')">
		here</A>.
</p>
<p>
	This sample also uses <b>DayRender</b> event to provide custom day cell rendering.
</p>
