<p>
This sample demonstrates the CallbackPanel's <span class="highlight">AutoDisableContents</span> 
property. The callback panel automatically disables its contents when this property
is set to true. This can be useful when you do not want user to accidentaly submit a form 
more than once.
</p>
<p>
<span class="highlight">LoadingPanelID</span> is usually used together with 
<span class="highlight">AutoDisableContents</span>. When LoadingPanelID is specified,
the CallbackPanel displays <span class="highlight">LoadingHTML</span> inside loading
panel.
</p>
